name: Generate Sponsors README
on:
  workflow_dispatch:
  schedule:
    - cron: 30 15 * * 0-6
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@v1.2.2
        with:
          token: ${{ secrets.SPONSOR_WORKFLOW_PAT }}
          file: 'README.md'

      - name: Update Github Readme 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: main
          folder: '.'
